In [1]:
list1=[17,2,8,23]
list2=[6,5,20,13]

In [2]:
list1+list2

[17, 2, 8, 23, 6, 5, 20, 13]

In [3]:
t1=(3,6,9,5)*3

In [4]:
t1

(3, 6, 9, 5, 3, 6, 9, 5, 3, 6, 9, 5)

In [5]:
import numpy as xy

In [6]:
list1_array=xy.array(list1)
list2_array=xy.array(list2)

In [7]:
list1_array+list2_array

array([23,  7, 28, 36])

In [8]:
t1_arr=xy.array(t1)
print(t1_arr)
print(type(t1_arr))

[3 6 9 5 3 6 9 5 3 6 9 5]
<class 'numpy.ndarray'>


In [9]:
(t1_arr)*3

array([ 9, 18, 27, 15,  9, 18, 27, 15,  9, 18, 27, 15])

In [10]:
arr0d=xy.array(90)
print(arr0d)
print(arr0d.ndim)
print(type(arr0d))

90
0
<class 'numpy.ndarray'>


In [11]:
arr1d=xy.array([25,89,43,16,33])
print(arr1d)
print(arr1d.ndim)
print(type(arr1d))

[25 89 43 16 33]
1
<class 'numpy.ndarray'>


In [12]:
arr2d=xy.array([[25,89,43,16,33],[5,6,8,2,10]])

In [13]:
### lists do not allow mathematical operations,but arrays aloow elementwise mathematical computations.
#### Lists support multiple data types,while arrays support only homogeneous data type.

In [14]:
arr1d=xy.array([25,89,43,16,33],dtype='float')
print(arr1d)
print(arr1d.ndim)
print(arr1d.dtype)


[25. 89. 43. 16. 33.]
1
float64


In [15]:
len(list1)

4

In [16]:
list1_array.size

4

In [18]:
import numpy as np
arr2d=np.array([[6,3,4,5],[1,2,3,4]])
arr2d

array([[6, 3, 4, 5],
       [1, 2, 3, 4]])

#### Attributes and methods of the array class

In [23]:
arr0d= np.array(50)
print(arr0d)
print(arr0d.ndim) # ndim gives us the number of dimensions in the array
print(arr0d.dtype) # returns the datatype of the elements in the array
print(arr0d.size) # returns the number of elements stored in the array

50
0
int32
1


In [25]:
arr1d=np.array([10,15,25,30])
print(arr1d)
print(arr1d.ndim) # ndim gives us the number of dimensions in the array
print(arr1d.dtype) # returns the datatype of the elements in the array
print(arr1d.size) # returns the number of elements stored in the array


[10 15 25 30]
1
int32
4


In [27]:
arr2d=np.array([[10,15,25,30],[2,5,6,8],[5,15,13,18]])
print(arr2d)
print(arr2d.ndim) # ndim gives us the number of dimensions in the array
print(arr2d.dtype) # returns the datatype of the elements in the array
print(arr2d.size) # returns the number of elements stored in the array
print(arr2d.shape) # returns the number of rows and columns in the array



[[10 15 25 30]
 [ 2  5  6  8]
 [ 5 15 13 18]]
2
int32
12
(3, 4)


* Every 1D data which we combine to create higher dimensional arrays should have the same size.
* If we find the product of the elements returned by the shape attribute,we get the size of the array

In [36]:
arr3d=np.array([[[1,8],[2,3]],[[4,5],[6,7]],[[8,9],[10,11]]])
print(arr3d)
print(arr3d.ndim) # ndim gives us the number of dimensions in the array
print(arr3d.dtype) # returns the datatype of the elements in the array
print(arr3d.size) # returns the number of elements stored in the array
print(arr3d.shape) # returns the number of 2D arrays we combine,number of rows in each 2D array, and columns in each 2D array


[[[ 1  8]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
3
int32
12
(3, 2, 2)


### add and remove dimensions of an array:

In [39]:
arr10=np.arange(1,13)
arr10

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [41]:
#convert this 1D array to 2D:
arr11=arr10.reshape(3,4)
print(arr11)
print(arr11.ndim)
print(arr11.shape)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
(3, 4)


In [43]:
##convert the 1D array to 3D array:
arr12=arr10.reshape(2,3,2)
print(arr12)
print(arr12.ndim)
print(arr12.shape)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3
(2, 3, 2)


#### To convert higher dimensional arrays to the lowest dimension(1D) we use two inbuilt methods of the array class. flatten() and ravel()

In [46]:
res1d=arr12.flatten()
res1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [48]:
res2=arr11.ravel()
res2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [50]:
### Q) Create a 1d array with 8 integer values. Name it 'a',then convert 'a' to a 2D array and name it 'b'
### In the third step convert 'b' to a 3D array 'c'.

In [52]:
#### Q) reduce the dimensions of 'c' to get back the original 1D data.

In [54]:
a=np.arange(1,9)
print(a)
print(a.ndim) # ndim gives us the number of dimensions in the array
print(a.dtype) # returns the datatype of the elements in the array
print(a.size) # returns the number of elements stored in the array


[1 2 3 4 5 6 7 8]
1
int32
8


In [56]:
b=a.reshape(2,4)
print(b)
print(b.ndim) # ndim gives us the number of dimensions in the array
print(b.dtype) # returns the datatype of the elements in the array
print(b.size) # returns the number of elements stored in the array
print(b.shape)

[[1 2 3 4]
 [5 6 7 8]]
2
int32
8
(2, 4)


In [58]:
c=a.reshape(2,2,2)
print(c)
print(c.ndim) # ndim gives us the number of dimensions in the array
print(c.dtype) # returns the datatype of the elements in the array
print(c.size) # returns the number of elements stored in the array
print(c.shape) # returns the number of 2D arrays we combine,number of rows in each 2D array, and columns in each 2D array


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
int32
8
(2, 2, 2)


In [60]:
a_1=b.flatten()
a_1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [62]:
a_2=c.ravel()
a_2

array([1, 2, 3, 4, 5, 6, 7, 8])

In [64]:
##convert c to a 2D array:
b_1=c.reshape(4,2)
b_1

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [66]:
#1d array:
arr13=np.arange(1,31)
arr13

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [68]:
##slice out elements 5-12
arr13[4:12]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [70]:
##read elements 26-30
arr13[-5:]

array([26, 27, 28, 29, 30])

In [79]:
#slice out 5,10,15,20:
arr13[4:20:5]

array([ 5, 10, 15, 20])

* The slicing syntax- start:stop:step
* skip=step-1

In [81]:
arr14=np.arange(1,10,2)
arr14

array([1, 3, 5, 7, 9])

In [83]:
arr15=np.arange(5,21,5)
arr15

array([ 5, 10, 15, 20])

In [85]:
arr16=np.arange(1,17,1).reshape(4,4)
arr16


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [87]:
arr16[2,1]

10

In [117]:
###Q) slice out elements of the fourth column

In [101]:
arr16[:,3]

array([ 4,  8, 12, 16])

In [91]:
###Q)slice out the 1st and 3rd rows of arr16

In [103]:
arr16[0:3:2,:]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [105]:
arr16[[0,2],:]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [93]:
###Q)reverse the rows of arr16

In [107]:
arr16[::-1,:]

array([[13, 14, 15, 16],
       [ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [95]:
###Q) reverse all columns of arr16

In [109]:
arr16[:,::-1]

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9],
       [16, 15, 14, 13]])

In [97]:
###Q)slice the values 10,11,12 from arr16

In [111]:
arr16[2,1:]

array([10, 11, 12])

In [99]:
###Q)slice elements 8,12 from arr16

In [113]:
arr16[1:3,3]

array([ 8, 12])

In [115]:
arr16[[1,2],3]

array([ 8, 12])

In [119]:
list2=[9,5,2,8,4]


In [121]:
list2[::-1]

[4, 8, 2, 5, 9]

In [123]:
tup12=(9,4,6,7)
tup12[::-1]

(7, 6, 4, 9)

In [1]:
import numpy as np

In [7]:
ar30=np.array([[5,6,7],[7,8,9],[10,11,12],[13,16,18]])
print(ar30)
print(ar30.shape)

[[ 5  6  7]
 [ 7  8  9]
 [10 11 12]
 [13 16 18]]
(4, 3)


In [5]:
### size of each 1D list gives us the no of columns in our 2D array,and the number of 1D lists we combine gives us the total number of rows in the 
### 2D array

In [9]:
copy_ar30=ar30.copy()

In [11]:
copy_ar30

array([[ 5,  6,  7],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 16, 18]])

In [13]:
copy_ar30[0,1]=60

In [15]:
copy_ar30

array([[ 5, 60,  7],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 16, 18]])

In [17]:
ar30

array([[ 5,  6,  7],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 16, 18]])

In [19]:
ar30[1,1:],ar30[2,1]

(array([8, 9]), 11)

In [21]:
print(copy_ar30[1,1],copy_ar30[1,2],copy_ar30[2,1])

8 9 11


#### Methods of the Array Class:

In [24]:
aar6=np.array([[0,2],[2,3]])
aar7=np.array([[4,5],[6,7]])

In [26]:
aar6

array([[0, 2],
       [2, 3]])

In [28]:
aar7

array([[4, 5],
       [6, 7]])

In [34]:
res1=np.concatenate((aar6,aar7),0) # when we have equal columns but unequal rows
res1

array([[0, 2],
       [2, 3],
       [4, 5],
       [6, 7]])

In [36]:
res2=np.concatenate((aar6,aar7),1)   #when we have equal rows in both arrays but unequal columns
res2

array([[0, 2, 4, 5],
       [2, 3, 6, 7]])

### axis=0 (default axis,implies rows) and axis=1(other axis,implies columns)

In [41]:
arr8=np.array([4,9,12,88,3,90,45])
sorted_array=np.sort(arr8)
sorted_array

array([ 3,  4,  9, 12, 45, 88, 90])

In [43]:
sorted_argsort=np.argsort(arr8) #returns the index positions of the sorted data
sorted_argsort

array([4, 0, 1, 2, 6, 3, 5], dtype=int64)

In [45]:
arg_max=np.argmax(arr8) #returns the index position of the max value.
arg_max

5

In [47]:
max1=np.max(arr8)
max1

90

In [49]:
arg_min=np.argmin(arr8)#returns the index position of the min value.
arg_min

4

In [51]:
min1=np.min(arr8)
min1

3

### where function in numpy works on two arrays,it returns a boolean value of true/false when a condition imposed on one of the array is satisfied. if its true,element of the main array is returned,but if the condition applied on the main array evaluates to a false,element of the secondary array is returned.

In [54]:
x=np.array([1,2,3,4])
y=np.array([10,13,17,21])

cond=x<3

result=np.where(cond,x,y)
result

array([ 1,  2, 17, 21])

In [56]:
a=np.array([4,5,6,7,8])
result=np.where((a>2)&(a<5),a,0)
result

array([4, 0, 0, 0, 0])