In [1]:
list1=[17,2,8,23]
list2=[6,5,20,13]

In [2]:
list1+list2

[17, 2, 8, 23, 6, 5, 20, 13]

In [3]:
t1=(3,6,9,5)*3

In [4]:
t1

(3, 6, 9, 5, 3, 6, 9, 5, 3, 6, 9, 5)

In [5]:
import numpy as xy

In [6]:
list1_array=xy.array(list1)
list2_array=xy.array(list2)

In [7]:
list1_array+list2_array

array([23,  7, 28, 36])

In [8]:
t1_arr=xy.array(t1)
print(t1_arr)
print(type(t1_arr))

[3 6 9 5 3 6 9 5 3 6 9 5]
<class 'numpy.ndarray'>


In [9]:
(t1_arr)*3

array([ 9, 18, 27, 15,  9, 18, 27, 15,  9, 18, 27, 15])

In [10]:
arr0d=xy.array(90)
print(arr0d)
print(arr0d.ndim)
print(type(arr0d))

90
0
<class 'numpy.ndarray'>


In [11]:
arr1d=xy.array([25,89,43,16,33])
print(arr1d)
print(arr1d.ndim)
print(type(arr1d))

[25 89 43 16 33]
1
<class 'numpy.ndarray'>


In [12]:
arr2d=xy.array([[25,89,43,16,33],[5,6,8,2,10]])

In [13]:
### lists do not allow mathematical operations,but arrays aloow elementwise mathematical computations.
#### Lists support multiple data types,while arrays support only homogeneous data type.

In [14]:
arr1d=xy.array([25,89,43,16,33],dtype='float')
print(arr1d)
print(arr1d.ndim)
print(arr1d.dtype)


[25. 89. 43. 16. 33.]
1
float64


In [15]:
len(list1)

4

In [16]:
list1_array.size

4

In [18]:
import numpy as np
arr2d=np.array([[6,3,4,5],[1,2,3,4]])
arr2d

array([[6, 3, 4, 5],
       [1, 2, 3, 4]])

#### Attributes and methods of the array class

In [23]:
arr0d= np.array(50)
print(arr0d)
print(arr0d.ndim) # ndim gives us the number of dimensions in the array
print(arr0d.dtype) # returns the datatype of the elements in the array
print(arr0d.size) # returns the number of elements stored in the array

50
0
int32
1


In [25]:
arr1d=np.array([10,15,25,30])
print(arr1d)
print(arr1d.ndim) # ndim gives us the number of dimensions in the array
print(arr1d.dtype) # returns the datatype of the elements in the array
print(arr1d.size) # returns the number of elements stored in the array


[10 15 25 30]
1
int32
4


In [27]:
arr2d=np.array([[10,15,25,30],[2,5,6,8],[5,15,13,18]])
print(arr2d)
print(arr2d.ndim) # ndim gives us the number of dimensions in the array
print(arr2d.dtype) # returns the datatype of the elements in the array
print(arr2d.size) # returns the number of elements stored in the array
print(arr2d.shape) # returns the number of rows and columns in the array



[[10 15 25 30]
 [ 2  5  6  8]
 [ 5 15 13 18]]
2
int32
12
(3, 4)


* Every 1D data which we combine to create higher dimensional arrays should have the same size.
* If we find the product of the elements returned by the shape attribute,we get the size of the array

In [36]:
arr3d=np.array([[[1,8],[2,3]],[[4,5],[6,7]],[[8,9],[10,11]]])
print(arr3d)
print(arr3d.ndim) # ndim gives us the number of dimensions in the array
print(arr3d.dtype) # returns the datatype of the elements in the array
print(arr3d.size) # returns the number of elements stored in the array
print(arr3d.shape) # returns the number of 2D arrays we combine,number of rows in each 2D array, and columns in each 2D array


[[[ 1  8]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
3
int32
12
(3, 2, 2)


### add and remove dimensions of an array:

In [39]:
arr10=np.arange(1,13)
arr10

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [41]:
#convert this 1D array to 2D:
arr11=arr10.reshape(3,4)
print(arr11)
print(arr11.ndim)
print(arr11.shape)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
(3, 4)


In [43]:
##convert the 1D array to 3D array:
arr12=arr10.reshape(2,3,2)
print(arr12)
print(arr12.ndim)
print(arr12.shape)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3
(2, 3, 2)


#### To convert higher dimensional arrays to the lowest dimension(1D) we use two inbuilt methods of the array class. flatten() and ravel()

In [46]:
res1d=arr12.flatten()
res1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [48]:
res2=arr11.ravel()
res2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [50]:
### Q) Create a 1d array with 8 integer values. Name it 'a',then convert 'a' to a 2D array and name it 'b'
### In the third step convert 'b' to a 3D array 'c'.

In [52]:
#### Q) reduce the dimensions of 'c' to get back the original 1D data.

In [54]:
a=np.arange(1,9)
print(a)
print(a.ndim) # ndim gives us the number of dimensions in the array
print(a.dtype) # returns the datatype of the elements in the array
print(a.size) # returns the number of elements stored in the array


[1 2 3 4 5 6 7 8]
1
int32
8


In [56]:
b=a.reshape(2,4)
print(b)
print(b.ndim) # ndim gives us the number of dimensions in the array
print(b.dtype) # returns the datatype of the elements in the array
print(b.size) # returns the number of elements stored in the array
print(b.shape)

[[1 2 3 4]
 [5 6 7 8]]
2
int32
8
(2, 4)


In [58]:
c=a.reshape(2,2,2)
print(c)
print(c.ndim) # ndim gives us the number of dimensions in the array
print(c.dtype) # returns the datatype of the elements in the array
print(c.size) # returns the number of elements stored in the array
print(c.shape) # returns the number of 2D arrays we combine,number of rows in each 2D array, and columns in each 2D array


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
int32
8
(2, 2, 2)


In [60]:
a_1=b.flatten()
a_1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [62]:
a_2=c.ravel()
a_2

array([1, 2, 3, 4, 5, 6, 7, 8])

In [64]:
##convert c to a 2D array:
b_1=c.reshape(4,2)
b_1

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [66]:
#1d array:
arr13=np.arange(1,31)
arr13

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [68]:
##slice out elements 5-12
arr13[4:12]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [70]:
##read elements 26-30
arr13[-5:]

array([26, 27, 28, 29, 30])

In [79]:
#slice out 5,10,15,20:
arr13[4:20:5]

array([ 5, 10, 15, 20])

* The slicing syntax- start:stop:step
* skip=step-1